language: node_js

node_js:
  - "0.10"

before_script:
  - git submodule update --init --recursive
  - npm install -g grunt-cli
  - grunt --version

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@239240
